# Generated by Django 2.2.6 on 2019-10-10 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='商品名称')),
                ('original_price', models.FloatField(verbose_name='商品原价')),
                ('actual_price', models.FloatField(verbose_name='商品现价')),
                ('freight', models.FloatField(verbose_name='商品运费')),
                ('image', models.ImageField(upload_to='uploads/commodity/%Y/%m/%d', verbose_name='商品图片')),
                ('detail', models.CharField(max_length=300, verbose_name='商品详情')),
                ('sale_nums', models.IntegerField(verbose_name='商品销量')),
                ('all_nums', models.IntegerField(verbose_name='商品库存')),
                ('comments_nums', models.IntegerField(verbose_name='商品评论量')),
                ('favor_nums', models.IntegerField(verbose_name='商品收藏量')),
                ('view_nums', models.IntegerField(verbose_name='商品浏览量')),
                ('created_time', models.DateTimeField(verbose_name='录入时间')),
            ],
            options={
                'verbose_name': '商品信息表',
            },
        ),
        migrations.CreateModel(
            name='CommodityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='分类名称')),
                ('level', models.IntegerField(verbose_name='分类级别')),
                ('uper_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commodity.CommodityType')),
            ],
            options={
                'verbose_name': '商品分类信息表',
            },
        ),
        migrations.CreateModel(
            name='CommodityDisplayFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='说明')),
                ('commodity_file', models.FileField(upload_to='uploads/commodity/%Y/%m/%d', verbose_name='展示图')),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commodity.Commodity')),
            ],
            options={
                'verbose_name': '商品文件信息表',
            },
        ),
        migrations.AddField(
            model_name='commodity',
            name='one_typename',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='one', to='commodity.CommodityType'),
        ),
        migrations.AddField(
            model_name='commodity',
            name='three_typename',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='three', to='commodity.CommodityType'),
        ),
        migrations.AddField(
            model_name='commodity',
            name='two_typename',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='two', to='commodity.CommodityType'),
        ),
    ]
